Repository cloudify-cosmo/cloudify-ui-components, pull requests merged in 2022-09, with the labels that each got.

#153 RD-5826 Upgrade `jest` to v29
  package-lock.json
  package.json
  test/__snapshots__/HtmlSnapshots.test.js.snap
Labels: dependencies, internal

#155 RD-5710 Allow using `index.ts` in components directories
  .eslintrc.json
  .storybook/main.js
  jest.config.js
  src/components/buttons/ApproveButton/index.ts
Labels: bug-fix, internal

#156 RD-5709 Rename all files to have .ts or .tsx extension - part 2 `test` folder & internal files
  .jest/enzyme.ts
  .jest/register-context.ts
  .jest/stub.ts
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview.ts
  .storybook/theme.ts
  README.md
  jest.config.js
  test/Checkmark.test.tsx
  test/Confirm.test.tsx
  test/DataSegment.test.tsx
  test/DataTable.test.tsx
  test/DateInput.test.tsx
  test/DateRangeInput.test.tsx
  test/EditableLabel.test.tsx
  test/ErrorMessage.test.tsx
  test/FileInput.test.tsx
  test/Form.test.tsx
  test/GenericField.test.tsx
  test/HtmlSnapshots.test.ts
  test/JsonInput.test.tsx
  test/Loading.test.tsx
  test/MessageContainer.test.tsx
  test/Pagination.test.tsx
  test/PopupConfirm.test.tsx
  test/PopupMenu.test.tsx
  test/ReadmeModal.test.tsx
  test/ResourceVisibility.test.tsx
  test/TimeInput.test.tsx
  test/UrlOrFileInput.test.tsx
  test/VisibilityField.test.tsx
  test/__snapshots__/HtmlSnapshots.test.ts.snap
Labels: internal

#161 RD-5598 Add UI testing guidelines link to PR template
  .github/pull_request_template.md
Labels: internal

#162 RD-5709 Fix babel config
  babel.config.js
Labels: bug-fix

#157 RD-5713: Updated popups components
  src/components/popups/Popup/Popup.stories.tsx
  src/components/popups/PopupConfirm/PopupConfirm.stories.tsx
  src/components/popups/PopupConfirm/PopupConfirm.tsx
  src/components/popups/PopupHelp/PopupHelp.stories.tsx
  src/components/popups/PopupHelp/PopupHelp.tsx
  src/components/popups/PopupMenu/PopupMenu.stories.tsx
  src/components/popups/PopupMenu/PopupMenu.tsx
  test/PopupConfirm.test.tsx
Labels: internal

#158 RD-5712: Migrated modals components
  src/components/cloudify/visibility/ResourceVisibility/ResourceVisibility.tsx
  src/components/modal/Alert/Alert.stories.tsx
  src/components/modal/Alert/Alert.tsx
  src/components/modal/Confirm/Confirm.stories.tsx
  src/components/modal/Confirm/Confirm.tsx
  src/components/modal/Modal/Modal.stories.tsx
  src/components/modal/ReadmeModal/ReadmeModal.stories.tsx
  src/components/modal/ReadmeModal/ReadmeModal.tsx
Labels: internal
