Repository cloudify-cosmo/cloudify-ui-components, pull requests merged in 2022-10, with the labels that each got.

#165 RD-5866: Adjusted popup offset
  src/components/popups/PopupHelp/PopupHelp.tsx
Labels: bug-fix

#166 RD-5956 Use new `cloudify-ui-common-*` packages
  .eslintrc.json
  .gitignore
  .prettierrc.js
  .storybook/manager.ts
  .storybook/theme.ts
  package-lock.json
  package.json
  src/components/form/JsonInput/JsonInput.tsx
  src/components/layout/FullScreenSegment/FullScreenSegment.tsx
  src/components/layout/HeaderBanner/HeaderBanner.tsx
  src/components/layout/HeaderBar/HeaderBar.tsx
  src/components/layout/Logo/Logo.tsx
  src/components/layout/ProductVersion/ProductVersion.tsx
  src/tsconfig.json
  test/tsconfig.json
Labels: internal

#160 RD-5715: Migrated visibility components
  .loki/reference/chrome_laptop_Data_KeyIndicator_External_Image.png
  .loki/reference/chrome_laptop_Data_KeyIndicator_Icon_With_Label.png
  .loki/reference/chrome_laptop_Data_KeyIndicator_Icon_With_Label_And_Number.png
  .loki/reference/chrome_laptop_Elements_Dropdown_Default.png
  .loki/reference/chrome_laptop_Elements_Dropdown_With_Empty_Option.png
  package-lock.json
  package.json
  src/components/cloudify/visibility/ResourceVisibility/ResourceVisibility.stories.tsx
  src/components/cloudify/visibility/ResourceVisibility/ResourceVisibility.tsx
  src/components/cloudify/visibility/VisibilityField/VisibilityField.stories.tsx
  src/components/cloudify/visibility/VisibilityField/VisibilityField.tsx
  src/components/cloudify/visibility/VisibilityIcon/VisibilityIcon.stories.tsx
  src/components/cloudify/visibility/VisibilityIcon/VisibilityIcon.tsx
  src/components/cloudify/visibility/consts.ts
  src/components/cloudify/visibility/types.ts
  src/components/data/HighlightText/HighlightText.tsx
  src/components/data/KeyIndicator/KeyIndicator.stories.tsx
  src/decorators/DivContainer.tsx
  src/decorators/LiveEdit/LiveEdit.tsx
  src/decorators/LiveEditDecorator.tsx
  test/__snapshots__/HtmlSnapshots.test.ts.snap
Labels: dependencies, internal

#169 RD-5715: Updated PopupConfirm typing
  src/components/popups/PopupConfirm/PopupConfirm.tsx
Labels: internal

#164 RD-1701 RD-2083 Switched table cell to semantic-ui-react, added stories
  .loki/reference/chrome_laptop_Data_DataTable_Vertical_align_and_text_align.png
  src/components/data/DataTable/DataTable.stories.tsx
  src/components/data/DataTable/DataTable.tsx
  src/components/data/DataTable/TableDataCell.tsx
  test/DataTable.test.tsx
  test/__snapshots__/HtmlSnapshots.test.ts.snap
Labels: feature, internal

#170 RD-5716, RD-4934 elements migration
  package-lock.json
  package.json
  src/components/elements/Checkmark/Checkmark.stories.tsx
  src/components/elements/Checkmark/Checkmark.tsx
  src/components/elements/Dropdown/Dropdown.stories.tsx
  src/components/elements/Dropdown/Dropdown.tsx
  src/components/elements/EditableLabel/EditableLabel.stories.tsx
  src/components/elements/EditableLabel/EditableLabel.tsx
  src/components/elements/ErrorMessage/ErrorMessage.stories.tsx
  src/components/elements/ErrorMessage/ErrorMessage.tsx
  src/components/elements/Loading/Loading.stories.tsx
  src/components/elements/Loading/Loading.tsx
  src/components/elements/LoadingOverlay/LoadingOverlay.stories.tsx
  src/components/elements/LoadingOverlay/LoadingOverlay.tsx
  src/components/elements/Menu/Menu.stories.tsx
  src/components/elements/MessageContainer/MessageContainer.stories.tsx
  src/components/elements/MessageContainer/MessageContainer.tsx
  test/EditableLabel.test.tsx
  test/ErrorMessage.test.tsx
  test/UrlOrFileInput.test.tsx
  test/__snapshots__/HtmlSnapshots.test.ts.snap
Labels: internal

#172 RD-5721: Migrated form components to typescript - Part 2
  src/components/form/DateInput/DateInput.tsx
  src/components/form/FieldLabel/FieldLabel.tsx
  src/components/form/Form/Form.stories.tsx
  src/components/form/Form/Form.tsx
  src/components/form/Form/FormDivider.stories.tsx
  src/components/form/Form/FormDivider.tsx
  src/components/form/Form/FormField.stories.tsx
  src/components/form/Form/FormField.tsx
  src/components/form/JsonInput/JsonInput.stories.tsx
  src/components/form/JsonInput/JsonInput.tsx
  src/components/form/JsonInput/ReactJsonViewWrapper.tsx
  src/components/form/TimeInput/TimeInput.tsx
  src/components/form/types.ts
  test/Confirm.test.tsx
  test/Form.test.tsx
  test/JsonInput.test.tsx
Labels: internal

#171 RD-5719 Ported table to typescript
  package-lock.json
  package.json
  src/components/data/DataTable/DataTable.stories.tsx
  src/components/data/DataTable/DataTable.tsx
  src/components/data/DataTable/DataTableContext.ts
  src/components/data/DataTable/TableColumn.tsx
  src/components/data/DataTable/TableDataExpandable.tsx
  src/components/data/DataTable/TableFilter.tsx
  src/components/data/DataTable/TableRow.tsx
  src/components/data/DataTable/TableRowExpandable.tsx
  test/DataTable.test.tsx
  test/__snapshots__/HtmlSnapshots.test.ts.snap
Labels: dependencies, internal

#174 RD-5717 NodesTree & HighlightText TS migration
  .loki/reference/chrome_laptop_Data_NodesTree_Collapsed.png
  .loki/reference/chrome_laptop_Data_NodesTree_Expanded.png
  .loki/reference/chrome_laptop_Data_NodesTree_Selectable.png
  .loki/reference/chrome_laptop_Data_NodesTree_With_Icons.png
  .loki/reference/chrome_laptop_Data_NodesTree_With_Tree_Data.png
  package-lock.json
  package.json
  src/components/data/HighlightText/HighlightText.stories.tsx
  src/components/data/NodesTree/NodesTree.css
  src/components/data/NodesTree/NodesTree.stories.tsx
  src/components/data/NodesTree/NodesTree.tsx
  test/__snapshots__/HtmlSnapshots.test.ts.snap
Labels: feature, internal
