Repository cloudify-cosmo/cloudify-ui-components, pull requests merged in 2022-06, with the labels that each got.

#134 RD-2537 Upgrade typescript eslint plugin
  package-lock.json
  package.json
Labels: internal

#135 RD-3666: FormField component enriched with error object support
  .loki/reference/chrome_laptop_Form_FormField_Error_With_Content.png
  src/components/elements/ErrorMessage/ErrorMessage.jsx
  src/components/form/Form/FormField.stories.jsx
  src/components/form/Form/FormField.tsx
  src/components/form/UrlOrFileInput/UrlOrFileInput.tsx
  test/__snapshots__/HtmlSnapshots.test.js.snap
Labels: feature

#138 RD-5267: scrollIntoView enhancement
  package-lock.json
  src/components/form/Form/Form.tsx
  test/__snapshots__/HtmlSnapshots.test.js.snap
Labels: bug-fix, feature
