Repository cloudify-cosmo/cloudify-ui-components, pull requests merged in 2022-11, with the labels that each got.

#178 RD-6391 Fix branch expressions in Jenkinsfile
  jenkins/Jenkinsfile
Labels: bug-fix

#177 RD-5343 added disabling next/forward in pagination buttons when appropriate
  src/components/data/DataTable/DataTable.stories.tsx
  src/components/data/common/Pagination/Pagination.tsx
  test/Pagination.test.tsx
  test/__snapshots__/HtmlSnapshots.test.ts.snap
Labels: feature

#182 RD-5881 update types/node to v16.11.68
  package-lock.json
  package.json
Labels: internal

#184 RD-6142 Fix Storybook stories typings
  src/components/buttons/ApproveButton/ApproveButton.stories.tsx
  src/components/buttons/CancelButton/CancelButton.stories.tsx
  src/components/buttons/CopyToClipboardButton/CopyToClipboard.stories.tsx
  src/components/cloudify/LabelsList/LabelsList.stories.tsx
  src/components/cloudify/visibility/ResourceVisibility/ResourceVisibility.stories.tsx
  src/components/cloudify/visibility/VisibilityField/VisibilityField.stories.tsx
  src/components/cloudify/visibility/VisibilityIcon/VisibilityIcon.stories.tsx
  src/components/data/KeyIndicator/KeyIndicator.stories.tsx
  src/components/elements/Checkmark/Checkmark.stories.tsx
  src/components/elements/Dropdown/Dropdown.stories.tsx
  src/components/elements/EditableLabel/EditableLabel.stories.tsx
  src/components/elements/ErrorMessage/ErrorMessage.stories.tsx
  src/components/elements/Loading/Loading.stories.tsx
  src/components/elements/LoadingOverlay/LoadingOverlay.stories.tsx
  src/components/elements/Menu/Menu.stories.tsx
  src/components/elements/MessageContainer/MessageContainer.stories.tsx
  src/components/form/Checkbox/Checkbox.stories.tsx
  src/components/form/ColorPicker/ColorPicker.stories.tsx
  src/components/form/DateInput/DateInput.stories.tsx
  src/components/form/DatePicker/DatePicker.stories.tsx
  src/components/form/DateRangeInput/DateRangeInput.stories.tsx
  src/components/form/FileInput/FileInput.stories.tsx
  src/components/form/Form/Form.stories.tsx
  src/components/form/Form/FormDivider.stories.tsx
  src/components/form/Form/FormField.stories.tsx
  src/components/form/GenericField/GenericField.stories.tsx
  src/components/form/TimeInput/TimeInput.stories.tsx
  src/components/form/UrlOrFileInput/UrlOrFileInput.stories.tsx
  src/components/layout/FullScreenSegment/FullScreenSegment.stories.tsx
  src/components/layout/HeaderBanner/HeaderBanner.stories.tsx
  src/components/layout/HeaderBar/HeaderBar.stories.tsx
  src/components/layout/HeaderMenu/HeaderMenu.stories.tsx
  src/components/layout/Logo/Logo.stories.tsx
  src/components/layout/MenusBar/MenusBar.stories.tsx
  src/components/layout/ProductVersion/ProductVersion.stories.tsx
  src/components/modal/Alert/Alert.stories.tsx
  src/components/modal/Confirm/Confirm.stories.tsx
  src/components/modal/Modal/Modal.stories.tsx
  src/components/modal/ReadmeModal/ReadmeModal.stories.tsx
  src/components/popups/Popup/Popup.stories.tsx
  src/components/popups/PopupConfirm/PopupConfirm.stories.tsx
  src/components/popups/PopupHelp/PopupHelp.stories.tsx
  src/components/popups/PopupMenu/PopupMenu.stories.tsx
Labels: internal
